config/routes.rb
Rails.application.routes.draw do
  resources :comments

  get 'tags' => 'tags#index'
  get 'tags/:tag', to: 'links#index', as: :tag

  resources :links do
    member do
      put "like", to:    "links#upvote"
      put "dislike", to: "links#downvote"
    end

    resources :comments
  end

  root to: "links#index"

  devise_for :users, 
             controllers: { omniauth_callbacks: "omniauth_callbacks" }

  resources :users
  
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

end

app/models/link.rb
class Link < ActiveRecord::Base
	acts_as_votable
	belongs_to :user
	has_many :comments
	has_many :taggings
	has_many :tags, through: :taggings

	# za link je obavezan title
  	validates :title, :presence => true

  	# validiranje inputa na osnovu rubijevog URI regularnog izraza
  	validates_format_of :url, :with => URI::regexp(%w(http https)), :allow_blank => true

	def self.search(search)
  		where("title LIKE ?", "%#{search}%")
	end

	def self.tagged_with(name)
		Tag.find_by_name!(name).links
	end

	def tag_list
		tags.map(&:name).join(", ")
	end

	def tag_list=(names)
		self.tags = names.split(",").map do |name|
			Tag.where(name: name.strip).first_or_create!
		end
	end

end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index, :show]

  respond_to :html

  def index
    @links = Link.all

    if params[:search]
      @links = Link.search(params[:search]).order('cast(created_at as date) desc, cached_votes_score desc').page(params[:page]).per_page(10)
    
    elsif params[:tag]
      @links = Link.tagged_with(params[:tag]).page(params[:page]).per_page(10)
    else
      @links = Link.all.order('cast(created_at as date) desc, cached_votes_score desc').page(params[:page]).per_page(10)
    end

    #@links = Link.all.page(params[:page]).per_page(10)
    #Link.order(created_at: :desc, cached_votes_up: :desc)
    respond_with(@links)
  end

  def show
    respond_with(@link)
  end

  def new
    #@link = Link.new
    @link = current_user.links.build
    respond_with(@link)
  end

  def edit
    @link = Link.find(params[:id])
  end

  def create
    @link = current_user.links.build(link_params)

      if @link.url.include? "youtube.com"

        @link.img_preview = "http://i.imgur.com/YD1Dk9T.png"

      elsif !@link.url.blank?

        require 'link_thumbnailer'
        @temp = LinkThumbnailer.generate(@link.url, verify_ssl: false)
        @link.img_preview = @temp.images.first.src.to_s

      else

        @link.img_preview = "http://i.imgur.com/heSD8Ik.jpg"

      end

    @link.save
    respond_with(@link)
  end

  def update
    @link.update(link_params)
    respond_with(@link)
  end

  def destroy
    @link.destroy
    respond_with(@link)
  end

  def upvote
    @link = Link.find(params[:id])

    if current_user.voted_for? @link
      redirect_to :back
    else
      @link.upvote_by current_user
      @link.user.increase_karma
      redirect_to :back
    end
  end

  def downvote
    @link = Link.find(params[:id])

    if current_user.voted_for? @link
      redirect_to :back
    else
      @link.downvote_by current_user
      @link.user.decrease_karma
      redirect_to :back
    end

  end

  private
    def set_link
      @link = Link.find(params[:id])
    end

    def link_params
      params.require(:link).permit(:title, :url, :body, :tag_list)
    end
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/links/_form.html.erb
<div class="col-md-6 col-md-offset-3 sign_up_form">
  <%= form_for(@link) do |f| %>
    <% if @link.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

        <ul>
        <% @link.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :url %><br>
      <%= f.text_field :url %>
    </div>
    <div class="field">
      <%= f.label :tag_list %><br>
      Add a few descriptive tags, separated by comma. Try to keep it up to five.<br>
      <%= f.text_field :tag_list %>
    </div>
    <div class="field">
      <%= f.label :body %><br>
      <%= f.text_area :body %>
    </div>

    <div class="new_link_rules">
    <strong>It's great you decided to share your content and thoughts with us. Before posting, please have in mind our few rules:</strong>
      <ul>
        <li>Please be civil and polite.</li>
        <li>Don't spam.</li>
        <li>Don't post adult content.</li>
        <li>Don't post illegal content.</li>
      </ul>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/links/edit.html.erb
<div class="row link-index-row"> 
  <div class="col-md-4 col-md-offset-4">
    <h1> <%= @title = "Editing link" %> </h1>
  </div>
</div>

 <% if current_user != nil %>
	<% if ((@link.user == current_user) or (current_user.is_admin == 1)) %>
		<%= render 'form' %>
	<% end %>
	<% else %>
	<div class="row">
		<center> You're trying to edit a story that's not yours. </center>
	</div>
<% end %>

app/views/links/index.html.erb
<div class="row link-index-row"> 
  <div class="col-md-4 col-md-offset-4">
    <h1> <%= @title = "DPLS - Trending content" %> </h1>
  </div>
</div>

  <% @links.each do |link| %>
    <div class="row link-index-row">
      <div class="col-md-1">
        <span class="upvote">
          <%= link_to like_link_path(link), method: :put, class: "upvote-image" do %>
          <% end %>
        </span>

        <span class="score">
          <%= link.cached_votes_score %>
        </span>

        <span class="downvote margin-down">
          <%= link_to dislike_link_path(link), method: :put, class: "downvote-image" do %>
          <% end %>
        </span>
      </div>

      <div class="col-md-2">
        <%= link_to link do %>
          <img src="<%= link.img_preview %>" alt="<%= link.title %>" class="story-img-preview img-responsive" />
        <% end %>
      </div>

      <div class="col-md-9">
        <% if !link.url.blank? %>
          <h2 class="link-index-title"><%= link_to link.title, link.url, :target => "_blank" %></h2>
        <% else %>
           <h2 class="link-index-title"><%= link_to link.title, link, :target => "_blank" %></h2>
        <% end %>
          
        <span class="link-index-meta">
          <strong class="link-index-discuss"><%= link_to "Join the discussion!", link, :target => "_blank" %></strong>
            Posted by <img src="<%= link.user.avatar %>"  class="link-index-user-avatar" alt = "<%= link.user.username %>" />
            <strong><%= link_to link.user.username, link.user %></strong> <%= time_ago_in_words(link.created_at) %> ago
        </span>

        <span class="link-index-tags"><%= raw link.tags.map(&:name).map { |t| link_to t, tag_path(t)}.join(' ') %></span>
      </div>

    </div>
  <% end %>

  <div class="row">
    <div class="col-md-4 col-md-offset-4 search-form">
      <%= form_tag(links_path, :method => "get") do %>
        <%= text_field_tag :search, params[:search] %>
        <%= submit_tag "Search", :name => nil %>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="browse-tags"><%= link_to "Browse all tags", tags_path %></div>
  </div>

  <center><%= will_paginate @links %></center>


<%#= link_to 'New Link', new_link_path %>

app/views/links/new.html.erb
<div class="row"> 
  <div class="col-md-4 col-md-offset-4">
    <h1> <%= @title = "DPLS - Submit a new link" %> </h1>
  </div>
</div>

<div class="row">
	<%= render 'form' %>
</div>

app/views/links/show.html.erb
<div class="row">
    <% if current_user != nil %>
      <% if ((@link.user == current_user) or (current_user.is_admin == 1)) %>
        <div class="btn-group pull-right">
          <%= link_to 'Edit', edit_link_path(@link), class: "btn btn-default" %>
          <%= link_to 'Delete', @link, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
        </div>
      <% end %>
    <% end %>
</div>

<div class="row link-index-row"> 
    <div class="col-md-1">
            <span class="upvote top-margin">
              <%= link_to like_link_path(@link), method: :put, class: "upvote-image" do %>
              <% end %>
            </span>

            <span class="score">
              <%#= @link.get_upvotes.size -  @link.get_downvotes.size %>
              <%= @link.cached_votes_score %>
            </span>

            <span class="downvote">
              <%= link_to dislike_link_path(@link), method: :put, class: "downvote-image" do %>
              <% end %>
            </span>
    </div>

    <div class="col-md-10">
      <span class="story-title"><h1> <%= @title = @link.title %> </h1></span>
    </div>

    <div class="col-md-1">
      <%= link_to @link.user do %>
        <img src="<%= @link.user.avatar %>"  class="story-show-user-avatar" alt = "<%= @link.user.username %>" />
      <% end %>
    </div>
</div>

<p id="notice"><%= notice %></p>

  <% if !@link.url.blank? %>
    <div class="row">
      <span class="visit-link"><%= link_to @link.title, @link.url %></center></span>
    </div>
  <% end %>

    <div class="row">
      <span class="link-show-tags"><%= raw @link.tags.map(&:name).map { |t| link_to t, tag_path(t)}.join(' ') %></span>
    </div>

  <% if !@link.body.blank? %>

    <div class="row">
      <div class="col-md-10 col-md-offset-1 story-body">
        <%= simple_format(@link.body) %>
      </div>
    </div>

  <% end %>

  <h3 class="comments-title">
    <%= @link.comments.count %> Comments
  </h3>

  <% if user_signed_in? %>
    <div class="row">
      <div class="col-md-5 col-md-offset-1 comment-form">
        <%= simple_form_for [@link, Comment.new] do |f| %>

          <div class="field">
            <%= f.text_area :body, class: "form-control" %>
          </div>
          <br />

          <%= f.submit "Add Comment", class: "submit-form-button" %>

        <% end %>
      </div>

      <div class="col-md-5 comment-rules">
        <h3 class="commenting-rules">Commenting rules</h3>
        
        <h4 class="commenting-rules">Think about the tone of your comment:</h4>
        <ul>
          <li>Be polite, friendly, and encouraging.</li>
          <li>Have some humour, but be careful with sarcasm.</li>
          <li>If you disagree, don’t be rude about it; give constructive (helpful) feedback.</li>
        </ul>

        <h4 class="commenting-rules">Think about the content of your comment:</h4>
        <ul>
          <li>Keep your comment on topic and make sense. Say something about the original post.</li>
          <li>Think very carefully about the links you share in your comments. Share links only if they're crucial for the discussion</li>
          <li>Avoid texting shortcuts like u for you and l8r for later, and only use one emoticon if you need to.</li>
        </ul>

        <h4 class="commenting-rules">Formatting:</h4>
        <ul>
          <li>You can use standard HTML tags to customize the look of your comment.</li>
        </ul>

      </div>
    </div>
  <% else %>
    Please login to post comments.
  <% end %>

  <%= render :partial => @link.comments %>